apiVersion: v1
kind: Service
metadata:
  name: clouddeploy
spec:
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 32000
      nodePort: 30000
  selector:
    app: clouddeploy
  type: NodePort